	"UberBoxBackDrop1"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBoxBackDrop1"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"1"
	"ypos"		"101"
	"zpos"		"-3"
	"wide"		"83"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"64 64 64 255"
	"alpha"		"255"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}

	"UberBoxBackDrop2"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBoxBackDrop1"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"109"
	"ypos"		"101"
	"zpos"		"-3"
	"wide"		"28"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"128 128 128 255"
	"alpha"		"255"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}


//For mediccharge.res
	"UberBox0"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox0"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"1"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox1"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox1"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"2"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox2"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox2"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"3"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox3"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox3"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"4"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox4"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox4"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"5"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox5"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox5"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"6"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox6"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox6"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"7"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox7"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox7"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"8"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox8"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox8"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"9"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox9"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox9"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"10"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox10"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox10"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"11"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox11"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox11"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"12"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox12"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox12"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"13"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox13"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox13"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"14"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox14"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox14"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"15"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox15"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox15"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"16"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox16"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox16"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"17"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox17"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox17"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"18"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox18"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox18"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"19"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox19"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox19"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"20"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox20"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox20"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"21"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox21"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox21"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"22"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox22"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox22"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"23"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox23"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox23"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"24"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox24"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox24"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"25"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox25"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox25"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"26"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox26"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox26"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"27"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox27"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox27"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"28"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox28"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox28"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"29"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox29"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox29"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"30"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox30"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox30"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"31"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox31"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox31"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"32"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox32"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox32"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"33"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox33"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox33"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"34"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox34"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox34"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"35"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox35"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox35"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"36"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox36"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox36"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"37"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox37"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox37"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"38"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox38"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox38"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"39"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox39"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox39"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"40"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox40"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox40"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"41"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox41"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox41"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"42"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox42"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox42"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"43"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox43"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox43"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"44"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox44"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox44"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"45"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox45"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox45"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"46"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox46"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox46"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"47"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox47"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox47"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"48"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox48"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox48"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"49"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox49"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox49"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"50"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox50"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox50"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"51"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox51"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox51"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"52"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox52"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox52"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"53"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox53"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox53"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"54"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox54"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox54"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"55"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox55"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox55"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"56"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox56"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox56"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"57"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox57"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox57"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"58"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox58"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox58"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"59"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox59"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox59"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"60"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox60"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox60"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"61"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox61"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox61"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"62"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox62"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox62"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"63"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox63"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox63"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"64"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox64"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox64"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"65"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox65"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox65"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"66"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox66"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox66"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"67"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox67"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox67"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"68"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox68"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox68"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"69"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox69"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox69"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"70"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox70"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox70"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"71"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox71"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox71"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"72"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox72"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox72"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"73"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox73"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox73"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"74"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox74"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox74"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"75"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox75"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox75"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"76"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox76"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox76"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"77"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox77"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox77"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"78"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox78"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox78"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"79"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox79"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox79"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"80"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox80"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox80"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"81"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox81"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox81"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"82"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox82"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox82"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"83"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox83"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox83"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"84"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox84"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox84"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"85"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox85"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox85"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"86"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox86"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox86"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"87"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox87"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox87"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"88"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox88"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox88"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"89"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox89"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox89"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"90"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox90"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox90"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"91"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox91"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox91"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"92"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox92"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox92"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"93"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox93"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox93"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"94"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox94"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox94"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"95"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox95"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox95"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"96"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox96"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox96"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"97"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox97"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox97"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"98"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
	"UberBox98"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox98"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"99"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
		"UberBox99"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox99"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"100"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
		"UberBox100"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox100"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"101"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
			"UberBox101"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox101"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"102"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
			"UberBox102"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox102"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"103"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
			"UberBox103"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox103"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"104"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
			"UberBox104"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox104"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"105"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
			"UberBox105"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox105"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"106"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
			"UberBox106"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox106"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"107"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
			"UberBox107"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox107"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"108"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
			"UberBox108"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox108"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"109"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
			"UberBox109"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox109"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"110"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
				"UberBox110"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox110"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"111"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
				"UberBox111"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox111"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"112"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
				"UberBox112"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox112"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"113"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
				"UberBox113"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox113"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"114"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
				"UberBox114"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox114"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"115"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
				"UberBox115"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox115"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"116"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
				"UberBox116"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox116"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"117"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
				"UberBox117"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox117"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"118"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
				"UberBox118"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox118"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"119"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
				"UberBox119"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox119"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"120"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
				"UberBox120"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox120"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"121"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
				"UberBox121"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox121"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"122"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
				"UberBox122"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox122"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"123"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
				"UberBox123"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox123"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"124"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
				"UberBox124"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox124"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"125"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
				"UberBox125"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox125"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"126"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
				"UberBox126"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox126"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"127"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
				"UberBox127"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox127"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"128"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
				"UberBox128"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox128"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"129"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
				"UberBox129"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox129"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"130"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
				"UberBox130"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox130"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"131"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
				"UberBox131"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox131"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"132"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
				"UberBox132"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox132"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"133"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
				"UberBox133"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox133"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"134"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
				"UberBox134"
	{
        "controlname"	"ImagePanel"
	"fieldname"	"UberBox134"
        "textAlignment"	"center"
	"font"		"CrosshairOL"
	"xpos"		"135"
	"ypos"		"101"
	"zpos"		"-2"
	"wide"		"2"
	"tall"		"6"
        "enabled"	"1"
        "visible"	"1"
	"fillcolor"	"255 255 255 255"
	"alpha"		"0"
	"defaultBgColor_Override"		"Blank"
	"PaintBackgroundType""0"
	}
}